version: '3'
networks:
  transfer_network: {}
services:
  app:
    build: .
    ports:
      - "8090:8090"
    environment:
      - APP_PORT=8090
      - APP_DOCUMENT_DB_HOST=mongo
      - APP_DOCUMENT_DB_PORT=27017
      - APP_DOCUMENT_DB_USERNAME=root
      - APP_DOCUMENT_DB_SECRET=rootpass
      - APP_DOCUMENT_DB_NAME=transfer_api
    networks:
      - transfer_network
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=transfer_api
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      transfer_network:
        aliases:
          - mongo
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
    networks:
      transfer_network:
        aliases:
          - mongo-express